version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: todo_db
      DB_PASSWORD: yourpassword
      DB_PORT: 5432
    ports:
      - "5001:5001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:

